spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_sqa?useSSL=false&serverTimezone=UTC
    username: root
    password: anhgdt1710
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  secretKey: ite@123!456
  expiration: 86400000
jackson:
  date-format: dd-MM-yyyy HH:mm:ss
  time-zone: Asia/Ho_Chi_Minh

# spring:
#   datasource:
#     driver-class-name: org.h2.Driver
#     url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#     username: sa
#     password: password
#   jpa:
#     generate-ddl: true
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#   h2:
#     console:
#       enabled: true
#       path: /h2-console
#   devtools:
#     restart:
#       enabled: true
#
# jwt:
#   secretKey: ite@123!456
#   expiration: 86400000
